### PR TITLE
fix: disable LanguageOption button double-clicks

### LINKED ISSUE #158: Prevent duplicate translations from being created when clicking “+ {language}” multiple times
Hi there. Thanks for sharing this plugin, it has been a great addition to our Sanity setup.

I have encountered an issue where a user can accidentally create duplicate translations of the same document from the “Translations” menu by clicking the same “+ {language}” button multiple times before the translated document has been created.

This can be reproduced in the following steps:

1. Create a base Sanity project with a single document type, e.g. `page`
2. Install the plugin, and configure Sanity to translate the document as per the plugin instructions.
3. Create a document in one language
4. Create a document translation via the “+ {language}” button in the “Translations” menu, and then click the same button again immediately after.
5. For each click until the first translated document is returned, a duplicate document will be created.

See video for demonstration.

https://github.com/sanity-io/document-internationalization/assets/42866396/9fc87a26-435b-4341-8731-7bea5e0fb309

It would be helpful to have a solution where when adding a translation, the “+ {language}” button is disabled after the first click until the translated document is created.

### PR DESCRIPTION
**Pull request by good-idea**
Currently, users can accidentally create multiple translations of a document (i.e. two Spanish documents) by clicking multiple times on the Language Option button. This is easy to do - after clicking the "Create" button, it looks like nothing is happening, so users are tempted to click it again.

Fixes #158 

Before: https://www.loom.com/share/181909ed1a1b42b89c037bcdfab1681b
After: https://www.loom.com/share/b464c41a6dbc4f8b90176b40d96fa725

### CODE REVIEW

File: src/components/LanguageOption.tsx [hunk 1]
```diff
@@ -57,6 +66,14 @@ export default function LanguageOption(props: LanguageOptionProps) {
   const open = useOpenInNewPane(translation?.value?._ref, schemaType.name)
   const handleOpen = useCallback(() => open(), [open])
 
+  /* Once a translation has been created, reset the userHasClicked state to false
+   * so they can click on it to navigate to the translation. If a translation already
+   * existed when this component was mounted, this will have no effect. */
+  const hasTranslation = Boolean(translation)
+  useEffect(() => {
+    setUserHasClicked(false)
```
Comment (bjoerge) [inline src/components/LanguageOption.tsx:74]: Any reason to keep this here vs in a `finally()` callback on the transaction promise? I guess it may take a bit of time before `translation` comes back as truthy?

Comment (good-idea) [reply src/components/LanguageOption.tsx:74]: yes, exactly.

While working I had originally put `setUserHasClicked(false)` within the promise - using not `finally()` but `then()` - but this resulted in a flash of content where:

- user clicks -> The button is disabled
- transaction resolves -> The button is no longer disabled but still showed the `+` icon
- `translation` becomes truthy -> The button is not disabled and shows the split-pane icon

This `useEffect` seemed more appropriate - we don't want the button to be clickable until the transaction has resolved **and** a translation is provided by the updated props.

Comment (good-idea) [reply src/components/LanguageOption.tsx:74]: (Sorry for the slow reply, I was OOO all last week)

Comment (bjoerge) [reply src/components/LanguageOption.tsx:74]: Makes sense, thanks for clarifying!

**Review by bjoerge — APPROVED** [review]
